language: go

go_import_path: github.com/LiveRamp/iabconsent

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

env:
  - GO111MODULE=on

install: true

script:
  - go test -v ./...
