package iabconsent_test

import (
	"github.com/StackAdapt/iabconsent"
	"time"
)

// Test fixtures can be created here: https://iabgpp.com/

var gppParsedConsentFixtures = map[string]map[int]*iabconsent.MspaParsedConsent{
	// Valid GPP w/ US National MSPA, No Subsection.
	"DBABL~BVVqAAEABAA": {7: {
		Version:                             1,
		SharingNotice:                       iabconsent.NoticeProvided,
		SaleOptOutNotice:                    iabconsent.NoticeProvided,
		SharingOptOutNotice:                 iabconsent.NoticeProvided,
		TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
		SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
		SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
		SaleOptOut:                          iabconsent.NotOptedOut,
		SharingOptOut:                       iabconsent.NotOptedOut,
		TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
		SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
			0:  iabconsent.ConsentNotApplicable,
			1:  iabconsent.ConsentNotApplicable,
			2:  iabconsent.ConsentNotApplicable,
			3:  iabconsent.ConsentNotApplicable,
			4:  iabconsent.ConsentNotApplicable,
			5:  iabconsent.ConsentNotApplicable,
			6:  iabconsent.ConsentNotApplicable,
			7:  iabconsent.NoConsent,
			8:  iabconsent.ConsentNotApplicable,
			9:  iabconsent.ConsentNotApplicable,
			10: iabconsent.ConsentNotApplicable,
			11: iabconsent.ConsentNotApplicable,
		},
		KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
			0: iabconsent.ConsentNotApplicable,
			1: iabconsent.ConsentNotApplicable,
		},
		PersonalDataConsents:    iabconsent.NoConsent,
		MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
		MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
		MspaServiceProviderMode: iabconsent.MspaNotApplicable,
		Gpc:                     false,
	},
	},
	// Valid GPP w/ US National MSPA, Subsection of GPC False.
	"DBABL~BVVqAAEABAA.QA": {7: {
		Version:                             1,
		SharingNotice:                       iabconsent.NoticeProvided,
		SaleOptOutNotice:                    iabconsent.NoticeProvided,
		SharingOptOutNotice:                 iabconsent.NoticeProvided,
		TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
		SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
		SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
		SaleOptOut:                          iabconsent.NotOptedOut,
		SharingOptOut:                       iabconsent.NotOptedOut,
		TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
		SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
			0:  iabconsent.ConsentNotApplicable,
			1:  iabconsent.ConsentNotApplicable,
			2:  iabconsent.ConsentNotApplicable,
			3:  iabconsent.ConsentNotApplicable,
			4:  iabconsent.ConsentNotApplicable,
			5:  iabconsent.ConsentNotApplicable,
			6:  iabconsent.ConsentNotApplicable,
			7:  iabconsent.NoConsent,
			8:  iabconsent.ConsentNotApplicable,
			9:  iabconsent.ConsentNotApplicable,
			10: iabconsent.ConsentNotApplicable,
			11: iabconsent.ConsentNotApplicable,
		},
		KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
			0: iabconsent.ConsentNotApplicable,
			1: iabconsent.ConsentNotApplicable,
		},
		PersonalDataConsents:    iabconsent.NoConsent,
		MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
		MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
		MspaServiceProviderMode: iabconsent.MspaNotApplicable,
		Gpc:                     false,
	},
	},
	// Valid GPP w/ US National MSPA, Subsection of GPC True.
	"DBABL~BVVqAAEABAA.YA": {7: {
		Version:                             1,
		SharingNotice:                       iabconsent.NoticeProvided,
		SaleOptOutNotice:                    iabconsent.NoticeProvided,
		SharingOptOutNotice:                 iabconsent.NoticeProvided,
		TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
		SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
		SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
		SaleOptOut:                          iabconsent.NotOptedOut,
		SharingOptOut:                       iabconsent.NotOptedOut,
		TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
		SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
			0:  iabconsent.ConsentNotApplicable,
			1:  iabconsent.ConsentNotApplicable,
			2:  iabconsent.ConsentNotApplicable,
			3:  iabconsent.ConsentNotApplicable,
			4:  iabconsent.ConsentNotApplicable,
			5:  iabconsent.ConsentNotApplicable,
			6:  iabconsent.ConsentNotApplicable,
			7:  iabconsent.NoConsent,
			8:  iabconsent.ConsentNotApplicable,
			9:  iabconsent.ConsentNotApplicable,
			10: iabconsent.ConsentNotApplicable,
			11: iabconsent.ConsentNotApplicable,
		},
		KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
			0: iabconsent.ConsentNotApplicable,
			1: iabconsent.ConsentNotApplicable,
		},
		PersonalDataConsents:    iabconsent.NoConsent,
		MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
		MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
		MspaServiceProviderMode: iabconsent.MspaNotApplicable,
		Gpc:                     true,
	},
	},
	// Valid GPP w/ US Virgina MSPA, Subsection of GPC False.
	"DBABRg~BVoYYYA": {9: {
		Version:                         1,
		SharingNotice:                   iabconsent.NoticeProvided,
		SaleOptOutNotice:                iabconsent.NoticeProvided,
		TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
		SaleOptOut:                      iabconsent.NotOptedOut,
		TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
		SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
			0: iabconsent.ConsentNotApplicable,
			1: iabconsent.NoConsent,
			2: iabconsent.Consent,
			3: iabconsent.ConsentNotApplicable,
			4: iabconsent.NoConsent,
			5: iabconsent.Consent,
			6: iabconsent.ConsentNotApplicable,
			7: iabconsent.NoConsent,
		},
		KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
			0: iabconsent.Consent,
		},
		MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
		MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
		MspaServiceProviderMode: iabconsent.MspaNotApplicable,
		Gpc:                     false,
	},
	},
	// Valid GPP w/ US US National and Virgina MSPA, Subsection of GPC False.
	"DBACLMA~BVVqAAEABAA~BVoYYYA": {
		iabconsent.SectionIDUSNAT: {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			SharingOptOut:                       iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
				0:  iabconsent.ConsentNotApplicable,
				1:  iabconsent.ConsentNotApplicable,
				2:  iabconsent.ConsentNotApplicable,
				3:  iabconsent.ConsentNotApplicable,
				4:  iabconsent.ConsentNotApplicable,
				5:  iabconsent.ConsentNotApplicable,
				6:  iabconsent.ConsentNotApplicable,
				7:  iabconsent.NoConsent,
				8:  iabconsent.ConsentNotApplicable,
				9:  iabconsent.ConsentNotApplicable,
				10: iabconsent.ConsentNotApplicable,
				11: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.NoConsent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNotApplicable,
			Gpc:                     false,
		},
		iabconsent.SectionIDUSVA: {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNotApplicable,
			Gpc:                     false,
		},
	},
	//
	"DBABBg~BVoAAACQ.QA": {
		iabconsent.SectionIDUSCA: {
			Version:                     1,
			SaleOptOutNotice:            iabconsent.NoticeProvided,
			SharingOptOutNotice:         iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice: iabconsent.NoticeProvided,
			SaleOptOut:                  iabconsent.NotOptedOut,
			SharingOptOut:               iabconsent.NotOptedOut,
			SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
				2: iabconsent.ConsentNotApplicable,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.ConsentNotApplicable,
				5: iabconsent.ConsentNotApplicable,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.ConsentNotApplicable,
				8: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.ConsentNotApplicable,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaYes,
			MspaServiceProviderMode: iabconsent.MspaNotApplicable,
		},
	},
}

// mixed of TCF, MSPA, US Privacy and CCPA
var gppParsedMixedConsent = map[string]map[int]iabconsent.GppParsedConsent{
	// Valid GPP string w/ sections for EU TCF V2 and US Privacy
	"DBACNYA~CPXuQIAPXuQIAAfKABENB-CgAAAAAAAAAAYgAAAAAAAA.YAAAAAAAAAAA~1YNN": {
		iabconsent.SectionIDEUTCFv2: &iabconsent.V2ParsedConsent{
			Version:                  2,
			Created:                  time.Date(2022, time.April, 20, 0, 0, 0, 0, time.UTC),
			LastUpdated:              time.Date(2022, time.April, 20, 0, 0, 0, 0, time.UTC),
			CMPID:                    31,
			CMPVersion:               640,
			ConsentScreen:            1,
			ConsentLanguage:          "EN",
			VendorListVersion:        126,
			TCFPolicyVersion:         2,
			IsServiceSpecific:        true,
			UseNonStandardStacks:     false,
			SpecialFeaturesOptIn:     map[int]bool{},
			PurposesConsent:          map[int]bool{},
			PurposesLITransparency:   map[int]bool{},
			PurposeOneTreatment:      false,
			PublisherCC:              "DE",
			MaxConsentVendorID:       0,
			IsConsentRangeEncoding:   false,
			ConsentedVendors:         map[int]bool{},
			NumConsentEntries:        0,
			ConsentedVendorsRange:    []*iabconsent.RangeEntry(nil),
			MaxInterestsVendorID:     0,
			IsInterestsRangeEncoding: false,
			InterestsVendors:         map[int]bool{},
			NumInterestsEntries:      0,
			InterestsVendorsRange:    []*iabconsent.RangeEntry(nil),
			NumPubRestrictions:       0,
			PubRestrictionEntries:    []*iabconsent.PubRestrictionEntry{},
			OOBDisclosedVendors:      (*iabconsent.OOBVendorList)(nil),
			OOBAllowedVendors:        (*iabconsent.OOBVendorList)(nil),
			PublisherTCEntry: &iabconsent.PublisherTCEntry{
				SegmentType:                  3,
				PubPurposesConsent:           map[int]bool{},
				PubPurposesLITransparency:    map[int]bool{},
				NumCustomPurposes:            0,
				CustomPurposesConsent:        map[int]bool{},
				CustomPurposesLITransparency: map[int]bool{},
			},
		},
		iabconsent.SectionIDUSPV1: &iabconsent.CcpaParsedConsent{
			Version:                1,
			Notice:                 iabconsent.CCPAYes,
			OptOutSale:             iabconsent.CCPANo,
			LSPACoveredTransaction: iabconsent.CCPANo,
		},
	},
	//Valid GPP w/ US National MSPA and US Privacy
	"DBABzw~1YNN~BVVqAAEABAA.QA": {
		iabconsent.SectionIDUSPV1: &iabconsent.CcpaParsedConsent{
			Version:                1,
			Notice:                 iabconsent.CCPAYes,
			OptOutSale:             iabconsent.CCPANo,
			LSPACoveredTransaction: iabconsent.CCPANo,
		},
		iabconsent.SectionIDUSNAT: &iabconsent.MspaParsedConsent{
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			SharingOptOut:                       iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
				0:  iabconsent.ConsentNotApplicable,
				1:  iabconsent.ConsentNotApplicable,
				2:  iabconsent.ConsentNotApplicable,
				3:  iabconsent.ConsentNotApplicable,
				4:  iabconsent.ConsentNotApplicable,
				5:  iabconsent.ConsentNotApplicable,
				6:  iabconsent.ConsentNotApplicable,
				7:  iabconsent.NoConsent,
				8:  iabconsent.ConsentNotApplicable,
				9:  iabconsent.ConsentNotApplicable,
				10: iabconsent.ConsentNotApplicable,
				11: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.NoConsent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNotApplicable,
		},
	},
	// EU TCF V2, US Privacy, and US National MSPA
	"DBACPeA~CPXuQIAPqd9YAAfKABENB-CgAAAAAAAAAAYgAAAAAAAA.YAAAAAAAAAAA~1YYY~BEBAAQAAAkA.QA": {
		iabconsent.SectionIDEUTCFv2: &iabconsent.V2ParsedConsent{
			Version:                  2,
			Created:                  time.Date(2022, time.April, 20, 0, 0, 0, 0, time.UTC),
			LastUpdated:              time.Date(2023, time.April, 19, 0, 0, 0, 0, time.UTC),
			CMPID:                    31,
			CMPVersion:               640,
			ConsentScreen:            1,
			ConsentLanguage:          "EN",
			VendorListVersion:        126,
			TCFPolicyVersion:         2,
			IsServiceSpecific:        true,
			UseNonStandardStacks:     false,
			SpecialFeaturesOptIn:     map[int]bool{},
			PurposesConsent:          map[int]bool{},
			PurposesLITransparency:   map[int]bool{},
			PurposeOneTreatment:      false,
			PublisherCC:              "DE",
			MaxConsentVendorID:       0,
			IsConsentRangeEncoding:   false,
			ConsentedVendors:         map[int]bool{},
			NumConsentEntries:        0,
			ConsentedVendorsRange:    []*iabconsent.RangeEntry(nil),
			MaxInterestsVendorID:     0,
			IsInterestsRangeEncoding: false,
			InterestsVendors:         map[int]bool{},
			NumInterestsEntries:      0,
			InterestsVendorsRange:    []*iabconsent.RangeEntry(nil),
			NumPubRestrictions:       0,
			PubRestrictionEntries:    []*iabconsent.PubRestrictionEntry{},
			OOBDisclosedVendors:      (*iabconsent.OOBVendorList)(nil),
			OOBAllowedVendors:        (*iabconsent.OOBVendorList)(nil),
			PublisherTCEntry: &iabconsent.PublisherTCEntry{
				SegmentType:                  3,
				PubPurposesConsent:           map[int]bool{},
				PubPurposesLITransparency:    map[int]bool{},
				NumCustomPurposes:            0,
				CustomPurposesConsent:        map[int]bool{},
				CustomPurposesLITransparency: map[int]bool{},
			},
		},
		iabconsent.SectionIDUSPV1: &iabconsent.CcpaParsedConsent{
			Version:                1,
			Notice:                 'Y',
			OptOutSale:             'Y',
			LSPACoveredTransaction: 'Y',
		},
		iabconsent.SectionIDUSNAT: &iabconsent.MspaParsedConsent{
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeNotApplicable,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeNotApplicable,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeNotApplicable,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeNotApplicable,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.OptOutNotApplicable,
			SharingOptOut:                       iabconsent.OptOutNotApplicable,
			TargetedAdvertisingOptOut:           iabconsent.OptOutNotApplicable,
			SensitiveDataProcessing: map[int]iabconsent.MspaConsent{
				0:  iabconsent.ConsentNotApplicable,
				1:  iabconsent.ConsentNotApplicable,
				2:  iabconsent.ConsentNotApplicable,
				3:  iabconsent.NoConsent,
				4:  iabconsent.ConsentNotApplicable,
				5:  iabconsent.ConsentNotApplicable,
				6:  iabconsent.ConsentNotApplicable,
				7:  iabconsent.ConsentNotApplicable,
				8:  iabconsent.ConsentNotApplicable,
				9:  iabconsent.ConsentNotApplicable,
				10: iabconsent.ConsentNotApplicable,
				11: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.ConsentNotApplicable,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaYes,
			MspaServiceProviderMode: iabconsent.MspaNotApplicable,
			Gpc:                     false,
		},
	},
}
