package iabconsent_test

import (
	"github.com/LiveRamp/iabconsent"
	"time"
)

// Test fixtures can be created here: https://iabgpp.com/

// var mspaConsentFixtures = map[string]map[string]int{"yes": {"dog": 1}}

var mspaConsentFixtures = map[int]map[string]*iabconsent.MspaParsedConsent{
	// UsNational
	iabconsent.UsNationalSID: {
		// usnat without false GPC subsection.
		"BVVqAAEABCA.QA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			SharingOptOut:                       iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.ConsentNotApplicable,
				1:  iabconsent.ConsentNotApplicable,
				2:  iabconsent.ConsentNotApplicable,
				3:  iabconsent.ConsentNotApplicable,
				4:  iabconsent.ConsentNotApplicable,
				5:  iabconsent.ConsentNotApplicable,
				6:  iabconsent.ConsentNotApplicable,
				7:  iabconsent.NoConsent,
				8:  iabconsent.ConsentNotApplicable,
				9:  iabconsent.ConsentNotApplicable,
				10: iabconsent.ConsentNotApplicable,
				11: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.NoConsent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
		},
		// usnat with true GPC subsection.
		"BVVqAAEABCA.YA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			SharingOptOut:                       iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.ConsentNotApplicable,
				1:  iabconsent.ConsentNotApplicable,
				2:  iabconsent.ConsentNotApplicable,
				3:  iabconsent.ConsentNotApplicable,
				4:  iabconsent.ConsentNotApplicable,
				5:  iabconsent.ConsentNotApplicable,
				6:  iabconsent.ConsentNotApplicable,
				7:  iabconsent.NoConsent,
				8:  iabconsent.ConsentNotApplicable,
				9:  iabconsent.ConsentNotApplicable,
				10: iabconsent.ConsentNotApplicable,
				11: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.NoConsent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
		// usnat without subsection.
		"BqqAqqqqqqA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                    iabconsent.NoticeNotProvided,
			SharingOptOutNotice:                 iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeNotProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeNotProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeNotProvided,
			SaleOptOut:                          iabconsent.OptOutNotApplicable,
			SharingOptOut:                       iabconsent.OptOutNotApplicable,
			TargetedAdvertisingOptOut:           iabconsent.OptOutNotApplicable,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.Consent,
				1:  iabconsent.Consent,
				2:  iabconsent.Consent,
				3:  iabconsent.Consent,
				4:  iabconsent.Consent,
				5:  iabconsent.Consent,
				6:  iabconsent.Consent,
				7:  iabconsent.Consent,
				8:  iabconsent.Consent,
				9:  iabconsent.Consent,
				10: iabconsent.Consent,
				11: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
	},
	// California
	iabconsent.UsCaliforniaSID: {
		// usca with subsection of GPC True.
		"BVoYYZoI.YA": {
			Version:                     1,
			SaleOptOutNotice:            iabconsent.NoticeProvided,
			SharingOptOutNotice:         iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice: iabconsent.NoticeProvided,
			SaleOptOut:                  iabconsent.NotOptedOut,
			SharingOptOut:               iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
				8: iabconsent.NotOptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
				1: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
		// usca without subsection.
		"BVoYYZoI": {
			Version:                     1,
			SaleOptOutNotice:            iabconsent.NoticeProvided,
			SharingOptOutNotice:         iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice: iabconsent.NoticeProvided,
			SaleOptOut:                  iabconsent.NotOptedOut,
			SharingOptOut:               iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
				8: iabconsent.NotOptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
				1: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
	},
	// Virginia
	iabconsent.UsVirginiaSID: {
		// usva with subsection of GPC True.
		"BVoYYYI.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
		// usva without subsection.
		"BVoYYYI": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
	},
	// Colorado
	iabconsent.UsColoradoSID: {
		// usco without GPC Subsection
		"BVoYYQg": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usco with subsection of GPC True.
		"BVoYYQg.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Utah
	iabconsent.UsUtahSID: {
		// usut with subsection of GPC False.
		"BVaGGGCA.QA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usut with subsection of GPC True.
		"BVaGGGCA.YA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Connecticut
	iabconsent.UsConnecticutSID: {
		// usct with subsection of GPC False.
		"BVoYYYQg": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.ConsentNotApplicable,
				2: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usct with subsection of GPC True.
		"BVoYYYQg.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.ConsentNotApplicable,
				2: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Florida
	iabconsent.UsFloridaSID: {
		// usfl with subsection of GPC False.
		"Bqqqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usfl with subsection of GPC True.
		"Bqqqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Montana
	iabconsent.UsMontanaSID: {
		// usmt with subsection of GPC False.
		"Bqqqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usmt with subsection of GPC True.
		"Bqqqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Oregon
	iabconsent.UsOregonSID: {
		// usor with subsection of GPC False.
		"BqqqqqqqoA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.Consent,
				1:  iabconsent.Consent,
				2:  iabconsent.Consent,
				3:  iabconsent.Consent,
				4:  iabconsent.Consent,
				5:  iabconsent.Consent,
				6:  iabconsent.Consent,
				7:  iabconsent.Consent,
				8:  iabconsent.Consent,
				9:  iabconsent.Consent,
				10: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usor with subsection of GPC True.
		"BqqqqqqqoA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.Consent,
				1:  iabconsent.Consent,
				2:  iabconsent.Consent,
				3:  iabconsent.Consent,
				4:  iabconsent.Consent,
				5:  iabconsent.Consent,
				6:  iabconsent.Consent,
				7:  iabconsent.Consent,
				8:  iabconsent.Consent,
				9:  iabconsent.Consent,
				10: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Texas
	iabconsent.UsTexasSID: {
		// ustx with subsection of GPC False.
		"BqqqqqqA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// ustx with subsection of GPC True.
		"BqqqqqqA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Delaware
	iabconsent.UsDelawareSID: {
		// usde with subsection of GPC False.
		"BqqqqqqqoA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usde with subsection of GPC True.
		"BqqqqqqqoA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Iowa
	iabconsent.UsIowaSID: {
		// usia with subsection of GPC False
		"BVVVVVVA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.OptedOut,
			TargetedAdvertisingOptOut:           iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
				1: iabconsent.NoConsent,
				2: iabconsent.NoConsent,
				3: iabconsent.NoConsent,
				4: iabconsent.NoConsent,
				5: iabconsent.NoConsent,
				6: iabconsent.NoConsent,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaYes,
			MspaOptOutOptionMode:    iabconsent.MspaYes,
			MspaServiceProviderMode: iabconsent.MspaYes,
			Gpc:                     false,
		},
		// usia with subsection of GPC True
		"BVVVVVVA.YA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.OptedOut,
			TargetedAdvertisingOptOut:           iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
				1: iabconsent.NoConsent,
				2: iabconsent.NoConsent,
				3: iabconsent.NoConsent,
				4: iabconsent.NoConsent,
				5: iabconsent.NoConsent,
				6: iabconsent.NoConsent,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaYes,
			MspaOptOutOptionMode:    iabconsent.MspaYes,
			MspaServiceProviderMode: iabconsent.MspaYes,
			Gpc:                     true,
		},
	},
	// Nebraska
	iabconsent.UsNebraskaSID: {
		// usne with subsection of GPC False
		"BmaqqqqA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usne with subsection of GPC True
		"BmaqqqqA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// New Hampshire
	iabconsent.UsNewHampshireSID: {
		// usnh with subsection of GPC False
		"Bpmqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usnh with subsection of GPC True
		"Bpmqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// New Jersey
	iabconsent.UsNewJerseySID: {
		// usnj with subsection of GPC False
		"BlWqqqmaqA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
				9: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.NoConsent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usnj with subsection of GPC True
		"BlWqqqmaqA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
				9: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.NoConsent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Tennessee
	iabconsent.UsTennesseeSID: {
		// ustn with subsection of GPC False
		"Bqqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// ustn with subsection of GPC True
		"Bqqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
}

var tcfeuV2ConsentFixtures = map[int]map[string]*iabconsent.V2ParsedConsent{
	iabconsent.EuropeTCFv2SID: {
		"CPXxRfAPXxRfAAfKABENB-CgAAAAAAAAAAYgAAAAAAAA": &iabconsent.V2ParsedConsent{
			Version:                  2,
			Created:                  time.Date(2022, 04, 20, 22, 00, 00, 0000, time.UTC),
			LastUpdated:              time.Date(2022, 04, 20, 22, 00, 00, 0000, time.UTC),
			CMPID:                    31,
			CMPVersion:               640,
			ConsentScreen:            1,
			ConsentLanguage:          "EN",
			VendorListVersion:        126,
			TCFPolicyVersion:         2,
			IsServiceSpecific:        true,
			UseNonStandardStacks:     false,
			SpecialFeaturesOptIn:     map[int]bool{},
			PurposesConsent:          map[int]bool{},
			PurposesLITransparency:   map[int]bool{},
			PurposeOneTreatment:      false,
			PublisherCC:              "DE",
			MaxConsentVendorID:       0,
			IsConsentRangeEncoding:   false,
			ConsentedVendors:         map[int]bool{},
			NumConsentEntries:        0,
			ConsentedVendorsRange:    nil,
			MaxInterestsVendorID:     0,
			IsInterestsRangeEncoding: false,
			InterestsVendors:         map[int]bool{},
			NumInterestsEntries:      0,
			InterestsVendorsRange:    nil,
			NumPubRestrictions:       0,
			PubRestrictionEntries:    []*iabconsent.PubRestrictionEntry{},
			OOBDisclosedVendors:      nil,
			OOBAllowedVendors:        nil,
		},
		"CPzyhEAPzyhEAEXdtAENDXCwAP_AAH_AACiQI9AB4C5EQCFDcHJNAIoUAAQDQIhAAAAgAAABgYAACBoAAIwAAAAwAAAAAAoCAAAAIABAAAEAAAAAAAEAAAAAAAEAAEAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiAAAAAIAEEAAAAACAAEAAAAAABAAAgAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAQQUgSAALAAqABcADIAHAAQAAkABkADQAHIAPAAfQBEAEUAJgATwApABfADMAGgAPwAhIBlAGWAOeAdwB3gEDgIOAhABFgCngF1AXmAyYBlgDPgGqgP3AgoAAAAA.YAAAAAAAAAAA": &iabconsent.V2ParsedConsent{
			Version:              2,
			Created:              time.Date(2023, 10, 17, 00, 00, 00, 0000, time.UTC),
			LastUpdated:          time.Date(2023, 10, 17, 00, 00, 00, 0000, time.UTC),
			CMPID:                279,
			CMPVersion:           1901,
			ConsentScreen:        0,
			ConsentLanguage:      "EN",
			VendorListVersion:    215,
			TCFPolicyVersion:     2,
			IsServiceSpecific:    true,
			UseNonStandardStacks: true,
			SpecialFeaturesOptIn: map[int]bool{},
			PurposesConsent: map[int]bool{
				1:  true,
				10: true,
				2:  true,
				3:  true,
				4:  true,
				5:  true,
				6:  true,
				7:  true,
				8:  true,
				9:  true,
			},
			PurposesLITransparency: map[int]bool{
				10: true,
				2:  true,
				3:  true,
				4:  true,
				5:  true,
				6:  true,
				7:  true,
				8:  true,
				9:  true,
			},
			PurposeOneTreatment:    false,
			PublisherCC:            "US",
			MaxConsentVendorID:     1146,
			IsConsentRangeEncoding: false,
			ConsentedVendors: map[int]bool{
				10:   true,
				1015: true,
				102:  true,
				104:  true,
				11:   true,
				1146: true,
				12:   true,
				120:  true,
				129:  true,
				13:   true,
				130:  true,
				132:  true,
				139:  true,
				143:  true,
				148:  true,
				173:  true,
				202:  true,
				203:  true,
				21:   true,
				210:  true,
				211:  true,
				23:   true,
				231:  true,
				238:  true,
				239:  true,
				24:   true,
				241:  true,
				25:   true,
				259:  true,
				263:  true,
				264:  true,
				28:   true,
				293:  true,
				294:  true,
				32:   true,
				335:  true,
				337:  true,
				345:  true,
				36:   true,
				373:  true,
				388:  true,
				410:  true,
				45:   true,
				458:  true,
				50:   true,
				506:  true,
				52:   true,
				524:  true,
				565:  true,
				57:   true,
				58:   true,
				60:   true,
				61:   true,
				62:   true,
				68:   true,
				69:   true,
				70:   true,
				73:   true,
				755:  true,
				759:  true,
				76:   true,
				79:   true,
				793:  true,
				80:   true,
				806:  true,
				812:  true,
				82:   true,
				849:  true,
				866:  true,
				91:   true,
				910:  true,
				929:  true,
				95:   true,
				97:   true,
			},
			NumConsentEntries:        0,
			ConsentedVendorsRange:    nil,
			MaxInterestsVendorID:     1044,
			IsInterestsRangeEncoding: true,
			InterestsVendors:         nil,
			NumInterestsEntries:      36,
			InterestsVendorsRange: []*iabconsent.RangeEntry{
				{
					StartVendorID: 11,
					EndVendorID:   11,
				}, {
					StartVendorID: 21,
					EndVendorID:   21,
				}, {
					StartVendorID: 23,
					EndVendorID:   23,
				}, {
					StartVendorID: 25,
					EndVendorID:   25,
				}, {
					StartVendorID: 28,
					EndVendorID:   28,
				}, {
					StartVendorID: 32,
					EndVendorID:   32,
				}, {
					StartVendorID: 36,
					EndVendorID:   36,
				}, {
					StartVendorID: 50,
					EndVendorID:   50,
				}, {
					StartVendorID: 52,
					EndVendorID:   52,
				}, {
					StartVendorID: 57,
					EndVendorID:   57,
				}, {
					StartVendorID: 60,
					EndVendorID:   60,
				}, {
					StartVendorID: 62,
					EndVendorID:   62,
				}, {
					StartVendorID: 68,
					EndVendorID:   69,
				}, {
					StartVendorID: 76,
					EndVendorID:   76,
				}, {
					StartVendorID: 79,
					EndVendorID:   79,
				}, {
					StartVendorID: 82,
					EndVendorID:   82,
				}, {
					StartVendorID: 95,
					EndVendorID:   95,
				}, {
					StartVendorID: 102,
					EndVendorID:   102,
				}, {
					StartVendorID: 104,
					EndVendorID:   104,
				}, {
					StartVendorID: 126,
					EndVendorID:   126,
				}, {
					StartVendorID: 132,
					EndVendorID:   132,
				}, {
					StartVendorID: 202,
					EndVendorID:   203,
				}, {
					StartVendorID: 231,
					EndVendorID:   231,
				}, {
					StartVendorID: 238,
					EndVendorID:   239,
				}, {
					StartVendorID: 259,
					EndVendorID:   259,
				}, {
					StartVendorID: 263,
					EndVendorID:   264,
				}, {
					StartVendorID: 278,
					EndVendorID:   278,
				}, {
					StartVendorID: 335,
					EndVendorID:   335,
				}, {
					StartVendorID: 373,
					EndVendorID:   373,
				}, {
					StartVendorID: 755,
					EndVendorID:   755,
				}, {
					StartVendorID: 806,
					EndVendorID:   806,
				}, {
					StartVendorID: 812,
					EndVendorID:   812,
				}, {
					StartVendorID: 830,
					EndVendorID:   830,
				}, {
					StartVendorID: 853,
					EndVendorID:   853,
				}, {
					StartVendorID: 1015,
					EndVendorID:   1015,
				}, {
					StartVendorID: 1044,
					EndVendorID:   1044,
				}},
			NumPubRestrictions:    0,
			PubRestrictionEntries: []*iabconsent.PubRestrictionEntry{},
			OOBDisclosedVendors:   nil,
			OOBAllowedVendors:     nil,
			PublisherTCEntry: &iabconsent.PublisherTCEntry{
				SegmentType:                  iabconsent.SegmentType(3),
				PubPurposesConsent:           map[int]bool{},
				PubPurposesLITransparency:    map[int]bool{},
				NumCustomPurposes:            0,
				CustomPurposesConsent:        map[int]bool{},
				CustomPurposesLITransparency: map[int]bool{},
			},
		},
	},
}

var ccpaConsentFixtures = map[int]map[string]*iabconsent.CcpaParsedConsent{
	// UsNational
	iabconsent.UsPVSID: {
		// usnat without false GPC subsection.
		"1---": &iabconsent.CcpaParsedConsent{
			Version:                1,
			Notice:                 '-',
			OptOutSale:             '-',
			LSPACoveredTransaction: '-',
		},
		"1YYY": &iabconsent.CcpaParsedConsent{
			Version:                1,
			Notice:                 'Y',
			OptOutSale:             'Y',
			LSPACoveredTransaction: 'Y',
		},
		"1NYN": &iabconsent.CcpaParsedConsent{
			Version:                1,
			Notice:                 'N',
			OptOutSale:             'Y',
			LSPACoveredTransaction: 'N',
		},
		"1NNN": &iabconsent.CcpaParsedConsent{
			Version:                1,
			Notice:                 'N',
			OptOutSale:             'N',
			LSPACoveredTransaction: 'N',
		},
	},
}

var tcfcaConsentFixtures = map[int]map[string]*iabconsent.V2CAParsedConsent{
	iabconsent.CanadaTCFSID: {
		"CPzyhEAPzyhEAEXdtAENDXCgAf-AAP-AAAj0AHgLkRAIUNwck0AihQABANAiEAAICAAAAGBgAAIGgAAjAAAADAAAAAACgIAAAAgAEAAAQAAAAAAAQAAAAAAAQAAQAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAAAAgAQQAAAAAIAAQAACAAAEAACAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAABBBSBKAAsACoAFwAMgAcABAACQAGQANAAcgA8AB9AEQARQAmABPACkAF8AMwAaAA_ACEAFLAMoAywBzwDuAO8AgcBBwEIAIsAU8AuoC8wGTAMsAZ8A1UB-4EFA": &iabconsent.V2CAParsedConsent{
			Version:                      2,
			Created:                      time.Date(2023, 10, 17, 00, 00, 00, 0000, time.UTC),
			LastUpdated:                  time.Date(2023, 10, 17, 00, 00, 00, 0000, time.UTC),
			CMPID:                        279,
			CMPVersion:                   1901,
			ConsentScreen:                0,
			ConsentLanguage:              "EN",
			VendorListVersion:            215,
			TCFPolicyVersion:             2,
			UseNonStandardStacks:         true,
			SpecialFeatureExpressConsent: map[int]bool{},
			PurposesExpressConsent: map[int]bool{
				1:  true,
				10: true,
				2:  true,
				3:  true,
				4:  true,
				5:  true,
				6:  true,
				7:  true,
				8:  true,
				9:  true,
			},
			PurposesImpliedConsent: map[int]bool{
				10: true,
				2:  true,
				3:  true,
				4:  true,
				5:  true,
				6:  true,
				7:  true,
				8:  true,
				9:  true,
			},
			MaxExpressConsentVendorID:     1146,
			IsExpressConsentRangeEncoding: false,
			ExpressConsentedVendors: map[int]bool{
				10:   true,
				1015: true,
				102:  true,
				104:  true,
				11:   true,
				1146: true,
				12:   true,
				120:  true,
				129:  true,
				13:   true,
				130:  true,
				132:  true,
				139:  true,
				143:  true,
				148:  true,
				165:  true,
				173:  true,
				202:  true,
				203:  true,
				21:   true,
				210:  true,
				211:  true,
				23:   true,
				231:  true,
				238:  true,
				239:  true,
				24:   true,
				241:  true,
				25:   true,
				259:  true,
				263:  true,
				264:  true,
				28:   true,
				293:  true,
				294:  true,
				32:   true,
				335:  true,
				337:  true,
				345:  true,
				36:   true,
				373:  true,
				388:  true,
				410:  true,
				45:   true,
				458:  true,
				50:   true,
				506:  true,
				52:   true,
				524:  true,
				565:  true,
				57:   true,
				58:   true,
				60:   true,
				61:   true,
				62:   true,
				68:   true,
				69:   true,
				70:   true,
				73:   true,
				755:  true,
				759:  true,
				76:   true,
				79:   true,
				793:  true,
				80:   true,
				806:  true,
				812:  true,
				82:   true,
				849:  true,
				866:  true,
				887:  true,
				91:   true,
				910:  true,
				929:  true,
				95:   true,
				97:   true,
			},
			NumExpressConsentEntries:      0,
			VendorExpressConsent:          nil,
			MaxImpliedConsentVendorID:     1044,
			IsImpliedConsentRangeEncoding: true,
			ImpliedConsentedVendors:       nil,
			NumImpliedConsentEntries:      37,
			VendorImpliedConsent: []*iabconsent.RangeEntry{
				{
					StartVendorID: 11,
					EndVendorID:   11,
				}, {
					StartVendorID: 21,
					EndVendorID:   21,
				}, {
					StartVendorID: 23,
					EndVendorID:   23,
				}, {
					StartVendorID: 25,
					EndVendorID:   25,
				}, {
					StartVendorID: 28,
					EndVendorID:   28,
				}, {
					StartVendorID: 32,
					EndVendorID:   32,
				}, {
					StartVendorID: 36,
					EndVendorID:   36,
				}, {
					StartVendorID: 50,
					EndVendorID:   50,
				}, {
					StartVendorID: 52,
					EndVendorID:   52,
				}, {
					StartVendorID: 57,
					EndVendorID:   57,
				}, {
					StartVendorID: 60,
					EndVendorID:   60,
				}, {
					StartVendorID: 62,
					EndVendorID:   62,
				}, {
					StartVendorID: 68,
					EndVendorID:   69,
				}, {
					StartVendorID: 76,
					EndVendorID:   76,
				}, {
					StartVendorID: 79,
					EndVendorID:   79,
				}, {
					StartVendorID: 82,
					EndVendorID:   82,
				}, {
					StartVendorID: 95,
					EndVendorID:   95,
				}, {
					StartVendorID: 102,
					EndVendorID:   102,
				}, {
					StartVendorID: 104,
					EndVendorID:   104,
				}, {
					StartVendorID: 126,
					EndVendorID:   126,
				}, {
					StartVendorID: 132,
					EndVendorID:   132,
				}, {
					StartVendorID: 165,
					EndVendorID:   165,
				}, {
					StartVendorID: 202,
					EndVendorID:   203,
				}, {
					StartVendorID: 231,
					EndVendorID:   231,
				}, {
					StartVendorID: 238,
					EndVendorID:   239,
				}, {
					StartVendorID: 259,
					EndVendorID:   259,
				}, {
					StartVendorID: 263,
					EndVendorID:   264,
				}, {
					StartVendorID: 278,
					EndVendorID:   278,
				}, {
					StartVendorID: 335,
					EndVendorID:   335,
				}, {
					StartVendorID: 373,
					EndVendorID:   373,
				}, {
					StartVendorID: 755,
					EndVendorID:   755,
				}, {
					StartVendorID: 806,
					EndVendorID:   806,
				}, {
					StartVendorID: 812,
					EndVendorID:   812,
				}, {
					StartVendorID: 830,
					EndVendorID:   830,
				}, {
					StartVendorID: 853,
					EndVendorID:   853,
				}, {
					StartVendorID: 1015,
					EndVendorID:   1015,
				}, {
					StartVendorID: 1044,
					EndVendorID:   1044,
				},
			},
		},
	},
}
