package iabconsent_test

import (
	"github.com/LiveRamp/iabconsent"
)

// Test fixtures can be created here: https://iabgpp.com/

// var mspaConsentFixtures = map[string]map[string]int{"yes": {"dog": 1}}

var mspaConsentFixtures = map[int]map[string]*iabconsent.MspaParsedConsent{
	// UsNational
	iabconsent.UsNationalSID: {
		// usnat v1 without false GPC subsection.
		"BVVqAAEABCA.QA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			SharingOptOut:                       iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.ConsentNotApplicable,
				1:  iabconsent.ConsentNotApplicable,
				2:  iabconsent.ConsentNotApplicable,
				3:  iabconsent.ConsentNotApplicable,
				4:  iabconsent.ConsentNotApplicable,
				5:  iabconsent.ConsentNotApplicable,
				6:  iabconsent.ConsentNotApplicable,
				7:  iabconsent.NoConsent,
				8:  iabconsent.ConsentNotApplicable,
				9:  iabconsent.ConsentNotApplicable,
				10: iabconsent.ConsentNotApplicable,
				11: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.NoConsent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
		},
		// usnat v1 with true GPC subsection.
		"BVVqAAEABCA.YA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			SharingOptOut:                       iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.ConsentNotApplicable,
				1:  iabconsent.ConsentNotApplicable,
				2:  iabconsent.ConsentNotApplicable,
				3:  iabconsent.ConsentNotApplicable,
				4:  iabconsent.ConsentNotApplicable,
				5:  iabconsent.ConsentNotApplicable,
				6:  iabconsent.ConsentNotApplicable,
				7:  iabconsent.NoConsent,
				8:  iabconsent.ConsentNotApplicable,
				9:  iabconsent.ConsentNotApplicable,
				10: iabconsent.ConsentNotApplicable,
				11: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.ConsentNotApplicable,
			},
			PersonalDataConsents:    iabconsent.NoConsent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
		// usnat v1 without subsection.
		"BqqAqqqqqqA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                    iabconsent.NoticeNotProvided,
			SharingOptOutNotice:                 iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeNotProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeNotProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeNotProvided,
			SaleOptOut:                          iabconsent.OptOutNotApplicable,
			SharingOptOut:                       iabconsent.OptOutNotApplicable,
			TargetedAdvertisingOptOut:           iabconsent.OptOutNotApplicable,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.Consent,
				1:  iabconsent.Consent,
				2:  iabconsent.Consent,
				3:  iabconsent.Consent,
				4:  iabconsent.Consent,
				5:  iabconsent.Consent,
				6:  iabconsent.Consent,
				7:  iabconsent.Consent,
				8:  iabconsent.Consent,
				9:  iabconsent.Consent,
				10: iabconsent.Consent,
				11: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usnat v2 with true GPC subsection.
		"CVVVVVVVVVVW.YA": {
			Version:                             2,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			SharingOptOutNotice:                 iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice:         iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.OptedOut,
			SharingOptOut:                       iabconsent.OptedOut,
			TargetedAdvertisingOptOut:           iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.NoConsent,
				1:  iabconsent.NoConsent,
				2:  iabconsent.NoConsent,
				3:  iabconsent.NoConsent,
				4:  iabconsent.NoConsent,
				5:  iabconsent.NoConsent,
				6:  iabconsent.NoConsent,
				7:  iabconsent.NoConsent,
				8:  iabconsent.NoConsent,
				9:  iabconsent.NoConsent,
				10: iabconsent.NoConsent,
				11: iabconsent.NoConsent,
				12: iabconsent.NoConsent,
				13: iabconsent.NoConsent,
				14: iabconsent.NoConsent,
				15: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
				1: iabconsent.NoConsent,
				2: iabconsent.NoConsent,
			},
			PersonalDataConsents:    iabconsent.NoConsent,
			MspaCoveredTransaction:  iabconsent.MspaYes,
			MspaOptOutOptionMode:    iabconsent.MspaYes,
			MspaServiceProviderMode: iabconsent.MspaYes,
			Gpc:                     true,
		},
	},

	// California
	iabconsent.UsCaliforniaSID: {
		// usca with subsection of GPC True.
		"BVoYYZoI.YA": {
			Version:                     1,
			SaleOptOutNotice:            iabconsent.NoticeProvided,
			SharingOptOutNotice:         iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice: iabconsent.NoticeProvided,
			SaleOptOut:                  iabconsent.NotOptedOut,
			SharingOptOut:               iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
				8: iabconsent.NotOptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
				1: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
		// usca without subsection.
		"BVoYYZoI": {
			Version:                     1,
			SaleOptOutNotice:            iabconsent.NoticeProvided,
			SharingOptOutNotice:         iabconsent.NoticeProvided,
			SensitiveDataLimitUseNotice: iabconsent.NoticeProvided,
			SaleOptOut:                  iabconsent.NotOptedOut,
			SharingOptOut:               iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
				8: iabconsent.NotOptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
				1: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
	},
	// Virginia
	iabconsent.UsVirginiaSID: {
		// usva with subsection of GPC True.
		"BVoYYYI.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
		// usva without subsection.
		"BVoYYYI": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
	},
	// Colorado
	iabconsent.UsColoradoSID: {
		// usco without GPC Subsection
		"BVoYYQg": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usco with subsection of GPC True.
		"BVoYYQg.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Utah
	iabconsent.UsUtahSID: {
		// usut with subsection of GPC False.
		"BVaGGGCA.QA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usut with subsection of GPC True.
		"BVaGGGCA.YA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:           iabconsent.NotOptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptOutNotApplicable,
				1: iabconsent.OptedOut,
				2: iabconsent.NotOptedOut,
				3: iabconsent.OptOutNotApplicable,
				4: iabconsent.OptedOut,
				5: iabconsent.NotOptedOut,
				6: iabconsent.OptOutNotApplicable,
				7: iabconsent.OptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Connecticut
	iabconsent.UsConnecticutSID: {
		// usct with subsection of GPC False.
		"BVoYYYQg": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.ConsentNotApplicable,
				2: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usct with subsection of GPC True.
		"BVoYYYQg.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.ConsentNotApplicable,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.ConsentNotApplicable,
				4: iabconsent.NoConsent,
				5: iabconsent.Consent,
				6: iabconsent.ConsentNotApplicable,
				7: iabconsent.NoConsent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.ConsentNotApplicable,
				2: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaNotApplicable,
			MspaOptOutOptionMode:    iabconsent.MspaNotApplicable,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Florida
	iabconsent.UsFloridaSID: {
		// usfl with subsection of GPC False.
		"Bqqqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usfl with subsection of GPC True.
		"Bqqqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Montana
	iabconsent.UsMontanaSID: {
		// usmt with subsection of GPC False.
		"Bqqqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usmt with subsection of GPC True.
		"Bqqqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Oregon
	iabconsent.UsOregonSID: {
		// usor with subsection of GPC False.
		"BqqqqqqqoA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.Consent,
				1:  iabconsent.Consent,
				2:  iabconsent.Consent,
				3:  iabconsent.Consent,
				4:  iabconsent.Consent,
				5:  iabconsent.Consent,
				6:  iabconsent.Consent,
				7:  iabconsent.Consent,
				8:  iabconsent.Consent,
				9:  iabconsent.Consent,
				10: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usor with subsection of GPC True.
		"BqqqqqqqoA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0:  iabconsent.Consent,
				1:  iabconsent.Consent,
				2:  iabconsent.Consent,
				3:  iabconsent.Consent,
				4:  iabconsent.Consent,
				5:  iabconsent.Consent,
				6:  iabconsent.Consent,
				7:  iabconsent.Consent,
				8:  iabconsent.Consent,
				9:  iabconsent.Consent,
				10: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Texas
	iabconsent.UsTexasSID: {
		// ustx with subsection of GPC False.
		"BqqqqqqA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// ustx with subsection of GPC True.
		"BqqqqqqA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Delaware
	iabconsent.UsDelawareSID: {
		// usde with subsection of GPC False.
		"BqqqqqqqoA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usde with subsection of GPC True.
		"BqqqqqqqoA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Iowa
	iabconsent.UsIowaSID: {
		// usia with subsection of GPC False
		"BVVVVVVA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.OptedOut,
			TargetedAdvertisingOptOut:           iabconsent.OptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptedOut,
				1: iabconsent.OptedOut,
				2: iabconsent.OptedOut,
				3: iabconsent.OptedOut,
				4: iabconsent.OptedOut,
				5: iabconsent.OptedOut,
				6: iabconsent.OptedOut,
				7: iabconsent.OptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaYes,
			MspaOptOutOptionMode:    iabconsent.MspaYes,
			MspaServiceProviderMode: iabconsent.MspaYes,
			Gpc:                     false,
		},
		// usia with subsection of GPC True
		"BVVVVVVA.YA": {
			Version:                             1,
			SharingNotice:                       iabconsent.NoticeProvided,
			SaleOptOutNotice:                    iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice:     iabconsent.NoticeProvided,
			SensitiveDataProcessingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                          iabconsent.OptedOut,
			TargetedAdvertisingOptOut:           iabconsent.OptedOut,
			SensitiveDataProcessingOptOuts: map[int]iabconsent.MspaOptout{
				0: iabconsent.OptedOut,
				1: iabconsent.OptedOut,
				2: iabconsent.OptedOut,
				3: iabconsent.OptedOut,
				4: iabconsent.OptedOut,
				5: iabconsent.OptedOut,
				6: iabconsent.OptedOut,
				7: iabconsent.OptedOut,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.NoConsent,
			},
			MspaCoveredTransaction:  iabconsent.MspaYes,
			MspaOptOutOptionMode:    iabconsent.MspaYes,
			MspaServiceProviderMode: iabconsent.MspaYes,
			Gpc:                     true,
		},
	},
	// Nebraska
	iabconsent.UsNebraskaSID: {
		// usne with subsection of GPC False
		"BmaqqqqA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usne with subsection of GPC True
		"BmaqqqqA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// New Hampshire
	iabconsent.UsNewHampshireSID: {
		// usnh with subsection of GPC False
		"Bpmqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usnh with subsection of GPC True
		"Bpmqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// New Jersey
	iabconsent.UsNewJerseySID: {
		// usnj with subsection of GPC False
		"BlWqqqmaqA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
				9: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.NoConsent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// usnj with subsection of GPC True
		"BlWqqqmaqA.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeProvided,
			SaleOptOut:                      iabconsent.OptedOut,
			TargetedAdvertisingOptOut:       iabconsent.OptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
				8: iabconsent.Consent,
				9: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.NoConsent,
				2: iabconsent.Consent,
				3: iabconsent.NoConsent,
				4: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaCoveredTransaction:  iabconsent.MspaNo,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
	// Tennessee
	iabconsent.UsTennesseeSID: {
		// ustn with subsection of GPC False
		"Bqqqqqo": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     false,
		},
		// ustn with subsection of GPC True
		"Bqqqqqo.YA": {
			Version:                         1,
			SharingNotice:                   iabconsent.NoticeNotProvided,
			SaleOptOutNotice:                iabconsent.NoticeNotProvided,
			TargetedAdvertisingOptOutNotice: iabconsent.NoticeNotProvided,
			SaleOptOut:                      iabconsent.NotOptedOut,
			TargetedAdvertisingOptOut:       iabconsent.NotOptedOut,
			SensitiveDataProcessingConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
				1: iabconsent.Consent,
				2: iabconsent.Consent,
				3: iabconsent.Consent,
				4: iabconsent.Consent,
				5: iabconsent.Consent,
				6: iabconsent.Consent,
				7: iabconsent.Consent,
			},
			KnownChildSensitiveDataConsents: map[int]iabconsent.MspaConsent{
				0: iabconsent.Consent,
			},
			PersonalDataConsents:    iabconsent.Consent,
			MspaOptOutOptionMode:    iabconsent.MspaNo,
			MspaServiceProviderMode: iabconsent.MspaNo,
			Gpc:                     true,
		},
	},
}
